SHOREWALL_CORE_VERSION_MAJOR = 5.2
SHOREWALL_CORE_VERSION = $(SHOREWALL_CORE_VERSION_MAJOR).8
SHOREWALL_CORE_SITE = https://shorewall.org/pub/shorewall/$(SHOREWALL_CORE_VERSION_MAJOR)/shorewall-$(SHOREWALL_CORE_VERSION)
SHOREWALL_CORE_SOURCE = shorewall-core-$(SHOREWALL_CORE_VERSION).tar.bz2

SHOREWALL_CORE_LICENSE = GPLv2 or later
SHOREWALL_CORE_LICENSE_FILES = LICENSE

define SHOREWALL_CORE_CONFIGURE
	$(@D)/configure --vendor=default --initfile=S41shorewall-core --confdir=/var/etc
endef
SHOREWALL_CORE_CONFIGURE_CMDS += $(SHOREWALL_CORE_CONFIGURE)

define SHOREWALL_CORE_INSTALL
	DESTDIR=$(TARGET_DIR) $(@D)/install.sh 
endef
SHOREWALL_CORE_INSTALL_TARGET_CMDS += $(SHOREWALL_CORE_INSTALL)

$(eval $(generic-package))
