#!/bin/sh
#
# Starts crond.
#

start() {
	printf "Starting crond: "
	umask 077

	start-stop-daemon -S -q -p /var/run/crond.pid \
		--exec /usr/sbin/crond -- -l 6
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping crond: "
	start-stop-daemon -K -q -p /var/run/crond.pid
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

